---
name: JS Actions

on:
  pull_request:
    types: [labeled]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: install-node-modules
        run: npm ci
        shell: bash
        working-directory: ./.github/actions/hello-world
      - name: hello-action
        uses: ./.github/actions/hello-world
